packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@langchain/anthropic@1.4.1'
  - '@langchain/core@1.1.49'
  - '@langchain/langgraph-checkpoint@1.1.1'
  - '@langchain/langgraph-sdk@1.9.22'
  - '@langchain/langgraph@1.4.2'
